openapi: 3.0.1
info:
  title: API di integrazione con pagoPA
  version: v1
  description: Api di integrazione al sistema di pagamento pagoPA
  license:
    name: PagoPA PN license
    url: http://pn.pagopa.it
servers:
  - url: https://placeholder
    description: placeholder
tags:
  - name: PaymentInfo
    description: Informazioni sullo stato del pagamento
paths:
  /ext-registry/pagopa/v1/paymentinfo/{paTaxId}/{noticeNumber}:
    get:
      deprecated: true
      operationId: getPaymentInfo
      summary: Retrieve payment information
      description: Use to enable payment button in notification detail page and display amount
      tags:
        - PaymentInfo
      security:                                                                # ONLY EXTERNAL
        - bearerAuth: [ ]                                                      # ONLY EXTERNAL
      parameters:
        - name: paTaxId
          description: Payment PA fiscal code
          in: path
          required: true
          example: '77777777777'
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/paTaxId'
        - name: noticeNumber
          description: Payment notice number  numero avviso
          in: path
          required: true
          example: '302000100000019421'
          schema:
            $ref: 'remote-refs.yaml#/components/schemas/noticeCode'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInfo'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
  /ext-registry/pagopa/v2.1/paymentinfo:
    post:
      operationId: getPaymentInfoV21
      summary: Retrieve payment information given a list of payments identifiers
      description: Use to enable payment buttons in notification detail page and display amount
      tags:
        - PaymentInfo
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/PaymentInfoRequests'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInfoResponse'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
  /ext-registry/pagopa/v1/checkout-cart:
    post:
      operationId: checkoutCart
      summary: Make a payment
      description: Make a payment by calling the Checkout API
      tags:
        - PaymentInfo
      security:                                                                # ONLY EXTERNAL
        - bearerAuth: [ ]                                                      # ONLY EXTERNAL
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '422':
          description: Unprocessable Entity
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
  /ext-registry-private/cost-update:
    post:
      operationId: UpdateNotificationCost
      description: This api allow updating notification fee 
      tags:
        - UpdateNotificationCost
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateNotificationCostRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateNotificationCostResponse'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
components:
  schemas:
    PaymentInfoRequests:
      title: Requests for payment info
      description: List of request payment info containing sender and payment id
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/PaymentInfoRequest'
    PaymentInfoRequest:
      title: Request for a payment info
      description: Object containing sender and payment id
      type: object
      properties:
        creditorTaxId:
          $ref: 'remote-refs.yaml#/components/schemas/paTaxId'
        noticeCode:
          $ref: 'remote-refs.yaml#/components/schemas/noticeCode'
      required:
        - creditorTaxId
        - noticeCode
    PaymentInfoResponse:
      title: Response for payment info requests
      description: List of payment info
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/PaymentInfoV21'
    PaymentInfoV21:
      title: Payment brief information
      description: Payment minimal information
      type: object
      required:
        - status
        - creditorTaxId
        - noticeCode
      properties:
        creditorTaxId:
          $ref: 'remote-refs.yaml#/components/schemas/paTaxId'
        noticeCode:
          $ref: 'remote-refs.yaml#/components/schemas/noticeCode'
        status:
          $ref: '#/components/schemas/PaymentStatus'
        detail:
          $ref: '#/components/schemas/Detail'
        detail_v2:
          $ref: '#/components/schemas/DetailV2'
        errorCode:
          description: error code to show at the user
          type: string
          example: PPT_AUTORIZZAZIONE
        amount:
          description: Amount for required payment in eurocents
          example: 1200
          type: integer
        url:
          description: Checkout base url used for check payment info
          example: https://api.uat.platform.pagopa.it/checkout/auth/payments/v2
          type: string
        causaleVersamento:
          description: reason for payment
          type: string
          example: Seconda rata TARI
        dueDate:
          description: payment expiration date
          type: string
          example: 2025-07-31
          pattern: ([0-9]{4})-(1[0-2]|0[1-9])-(0[1-9]|1[0-9]|2[0-9]|3[0-1])
    PaymentInfo:
      title: Payment brief information
      description: Payment minimal information
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/PaymentStatus'
        detail:
          $ref: '#/components/schemas/Detail'
        detail_v2:
          $ref: '#/components/schemas/DetailV2'
        errorCode:
          description: error code to show at the user
          type: string
          example: PPT_AUTORIZZAZIONE
        amount:
          description: Amount for required payment in eurocents
          example: 1200
          type: integer
        url:
          description: Checkout base url used for check payment info
          example: https://api.uat.platform.pagopa.it/checkout/auth/payments/v2
          type: string
    PaymentStatus:
      title: Payment status
      example: 'REQUIRED'
      description: >
        Payment status:
          * `REQUIRED` - payment required
          * `SUCCEEDED` - payment done
          * `IN_PROGRESS` - waiting confirm
          * `FAILURE` - error see errorType
      type: string
      enum:
        - REQUIRED
        - SUCCEEDED
        - IN_PROGRESS
        - FAILURE
    Detail:
      title: Error classification
      description: >
        Classification to help user address the issue
          * `PAYMENT_UNAVAILABLE`: Technical Error.
          * `PAYMENT_UNKNOWN`: Payment data error.
          * `DOMAIN_UNKNOWN`: creditor institution error.
          * `PAYMENT_ONGOING`: payment on going.
          * `PAYMENT_EXPIRED`: payment expired.
          * `PAYMENT_CANCELED`: payment cancelled.
          * `PAYMENT_DUPLICATED`: payment duplicated.
          * `GENERIC_ERROR`: generic error.
      example: PAYMENT_UNAVAILABLE
      type: string
      enum:
        - PAYMENT_UNAVAILABLE
        - PAYMENT_UNKNOWN
        - DOMAIN_UNKNOWN
        - PAYMENT_ONGOING
        - PAYMENT_EXPIRED
        - PAYMENT_CANCELED
        - PAYMENT_DUPLICATED
        - GENERIC_ERROR
    DetailV2:
      title: Error classification detail
      description: >
        Classification detail to help user address the issue
      example: PPT_PSP_SCONOSCIUTO
      type: string
    PaymentRequest:
      title: Request to make a payment on Checkout
      type: object
      required:
        - paymentNotice
        - returnUrl
      properties:
        paymentNotice:
          $ref: '#/components/schemas/PaymentNotice'
        returnUrl:
          description: Checkout base url used to make payment
          example: https://api.uat.platform.pagopa.it/checkout/auth/payments/v2
          type: string
          maxLength: 2048
          pattern: ^[ -~ ]*$
    PaymentNotice:
      title: Request for a Payment Notice
      description: Information of a Payment Notice
      type: object
      required:
        - noticeNumber
        - fiscalCode
        - amount
        - companyName
        - description
      properties:
        noticeNumber:
          type: string
          description: The payment notice number
          minLength: 18
          maxLength: 18
          pattern: '^\d+$'
        fiscalCode:
          type: string
          description: Public Administration tax code
          minLength: 11
          maxLength: 11
          pattern: '^\d+$'
        amount:
          type: integer
          description: Amount ( in euro cents ) of the payment notice
          minimum: 1
        companyName:
          type: string
          description: Public Administration company name
          maxLength: 250
          pattern: ^([\x20-\xFF]{1,250})$
        description:
          type: string
          description: Subject of payment
          maxLength: 250
          pattern: ^([\x20-\xFF]{1,250})$
    PaymentResponse:
      title: Response containing the Checkout callback URL
      type: object
      required:
        - checkoutUrl
      properties:
        checkoutUrl:
          type: string
          description: The Checkout callback URL
    
    UpdateNotificationCostRequest:
      title: Update notification cost information
      type: object
      required:
        - notificationStepCost
        - iun
        - paymentsInfoForRecipients
        - updateCostPhase
      properties:
        notificationStepCost:
          type: integer
          description: Single notification step cost (euro-cent)
          format: int32
        iun:
          description: Notification Unique identifier
          type: string
        paymentsInfoForRecipients:
          type: array
          description: Payment information for recipient
          items:
            $ref: '#/components/schemas/PaymentsInfoForRecipient'
        eventTimestamp:
          type: string
          description: event timestamp
          format: date-time
        eventStorageTimestamp:
          type: string
          description: event storage timestamp
          format: date-time
        updateCostPhase:
          type: string
          enum:
            - VALIDATION
            - REQUEST_REFUSED
            - NOTIFICATION_CANCELLED
            
    PaymentsInfoForRecipient:
      title: Payment information for recipient
      type: object
      required:
        - recIndex
        - creditorTaxId
        - noticeCode
      properties:
        recIndex:
          type: integer
          description: recipient index
          format: int32
        creditorTaxId:
          description: Payment PA fiscal code
          example: '77777777777'
          type: string
          maxLength: 11
          minLength: 11
        noticeCode:
          description: Payment notice number  numero avviso
          example: '302000100000019421'
          type: string
          maxLength: 18
          minLength: 18
      
    UpdateNotificationCostResponse:
      title: Update notification cost response
      type: object
      required:
        - updateResults
      properties:
        updateResults:
          type: array
          description: Update notification cost results
          items:
            $ref: '#/components/schemas/UpdateNotificationCostResult'
    
    UpdateNotificationCostResult:
      title: Update notification cost results
      type: object
      required:
        - recIndex
        - creditorTaxId
        - noticeCode
        - result
      properties:
        recIndex:
          type: integer
          description: recipient index
          format: int32
        creditorTaxId:
          description: Payment PA fiscal code
          example: '77777777777'
          type: string
          maxLength: 11
          minLength: 11
        noticeCode:
          description: Payment notice number  numero avviso
          example: '302000100000019421'
          type: string
          maxLength: 18
          minLength: 18
        result:
          type: string
          enum:
            - OK
            - KO
            - RETRY

  securitySchemes:                                      # ONLY EXTERNAL
    bearerAuth:                                         # ONLY EXTERNAL
      type: http                                        # ONLY EXTERNAL
      scheme: bearer                                    # ONLY EXTERNAL
      bearerFormat: JWT                                 # ONLY EXTERNAL
security:                                               # ONLY EXTERNAL
 - bearerAuth: []                                       # ONLY EXTERNAL
