openapi: 3.0.1
info:
  title: API di integrazione con pagoPA
  version: v1
  description: Api di integrazione al sistema di pagamento pagoPA
  license:
    name: PagoPA PN license
    url: http://pn.pagopa.it
servers:
  - url: https://placeholder
    description: placeholder
tags:
  - name: PaymentInfo
    description: Informazioni sullo stato del pagamento
paths:
  /ext-registry/pa/v1/paymentinfo/{paymentId}:
    get:
      operationId: getPaymentInfo
      summary: Retrieve payment information
      description: Use to enable payment button in notification detail page and amount
      tags:
        - PaymentInfo
      parameters:
        - name: paymentId
          description: Payment identifier composed by fiscal code and notice number (numero avviso)
          in: path
          required: true
          schema:
            type: string
            maxLength: 29
            minLength: 29
            pattern: '^\d+$'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInfo'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'pn-errors.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'pn-errors.yaml#/components/schemas/Problem'
components:
  schemas:
    PaymentInfo:
      title: Payment brief information
      description: Payment minimal information
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/PaymentStatus'
        amount:
          description: Amount for required payment in eurocents
          type: integer
    PaymentStatus:
      title: Payment status
      description: >
        Payment status:
          * `required` - payment required
          * `succeeded` - payment done
          * `in progress` - waiting confirm 
          * `failed` - error
      type: string
      enum:
        - required
        - succeeded
        - in progress
        - failed

