openapi: 3.0.1
info:
  title: Get recipients digital addresses from national public registries
  version: v1
  description: |
      # Fare una descrizione
  license:
    name: PagoPA PN license
    url: http://pippo.pappo.it
servers:
  - url: https://servizio-anonimizzazione
    description: finto
tags:
  - name: InfoDomicile
    description: Domicile addresses
paths:
  '/ext-registry-private/domiciles/v1/{recipientType}/{opaqueId}/digital':
    get:
      operationId: getOneDigitalDomicile
      summary: Read the digital domicile of a notification recipient
      description: |
          Read the digital domicile of a notification recipient. Il destinatario 
          può essere una persona fisica o una persona giuridica.
      tags:
        - InfoDomicile
      parameters:
        - name: recipientType
          description: il tipo del destinatario
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/RecipientType'
        - name: opaqueId
          description: Identificativo universale univoco del destinatario
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/OpaqueId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalDomicile'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
  '/ext-registry-private/domiciles/v1/{recipientType}/{opaqueId}/analog':
    get:
      operationId: getOneAnalogDomicile
      summary: Read the analog domicile of a notification recipient
      description: |
          Read the analog domicile of a notification recipient. Il destinatario 
          può essere una persona fisica o una persona giuridica.
      tags:
        - InfoDomicile
      parameters:
        - name: recipientType
          description: il tipo del destinatario
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/RecipientType'
        - name: opaqueId
          description: Identificativo universale univoco del destinatario
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/OpaqueId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalogDomicile'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
components:
  schemas:
    RecipientType:
      title: 'Tipo del destinatario: PF / PG'
      type: string
      enum:
        - PF
        - PG
    OpaqueId:
      title: |
          Identificati Univoco Universale del destinatario della notifica di cui si 
          sta richiedendo il domicilio analogico o digitale.
      type: string
      format: uuid
    DigitalDomicile:
      title: dettagli di un domicilio digitale
      type: object
      required:
        - domicileType
        - address
      properties:
        domicileType:
          type: string
          enum:
            - PEC
            - IO
        address:
          type: string
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
    AnalogDomicile:
      title: dettagli di un domicilio analogico; ovvero un indirizzo fisico
      type: object
      required:
        - address
        - cap
        - municipality
        - province
      properties:
        at:
          type: string
          example: 'presso famiglia Rossi'
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
        address: 
          type: string
          example: 'Via senza Nome 15'
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
        addressDetails:
          type: string
          example: 'scala A'
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
        cap:
          type: string
          example: '40129'
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
        municipality:
          type: string
          example: 'Bologna'
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
        province:
          type: string
          minLength: 2
          maxLength: 2
          example: 'BO'
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
        state:
          type: string
          minLength: 2
          maxLength: 2
          example: 'it'
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
