openapi: 3.0.1
info:
  x-api-id: api-external-selfcare-b2b-pa
  x-summary: API B2B per recuperare i gruppi delle Pubbliche Amministrazioni
  title: API di integrazione con self care
  version: 1.0.0
  description: Api di integrazione al sistema Self Care
  contact:
    email: pn-supporto-enti@pagopa.it
  license:
    name: Licenza di PN
    url: https://notifichedigitali.pagopa.it/pubbliche-amministrazioni/index.html
  termsOfService: https://notifichedigitali.pagopa.it/pubbliche-amministrazioni/index.html
servers:
  - url: https://placeholder
    description: placeholder
tags:
  - name: SelfCare
    description: Integrazione verso portale selfcare
paths:
  /ext-registry-b2b/pa/v1/groups:
    get:
      operationId: getGroupsB2B
      summary: Retrieve group of current user defined in Self Care
      description: |
        PA can use groups to better organize work in its organization. Return the PaGroupList of the current user, or if the user isn't in some group, all the groups of the current PA
      tags:
        - InfoPA
      security:
        - ApiKeyAuth: []
      parameters:
        - name: statusFilter
          description: Se valorizzato indica di tornare solo i gruppi nello stato passato
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/PaGroupStatus'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaGroupList'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /status:
    get:
      summary: healthCheck path
      description: health check path per verificare lo stato del micro servizio
      tags:
        - HealthCheck
      operationId: status
      responses:
        '200':
          description: Ok
        '500':
          description: Internal Server Error
components:
  schemas:
    PaNameFilter:
      title: Admitted character for PA denomination field
      type: string
      minLength: 3
      maxLength: 250
      pattern: ^([\x20-\xFF]{1,250})$
    PaSummary:
      title: PA in short
      description: PA with minimal information
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/SelfCarePaId'
        name:
          type: string
    PaSummariesList:
      title: Brief list of PAs
      description: Contains a list of PA with minimal information
      type: array
      items:
        $ref: '#/components/schemas/PaSummary'
    PaInfo:
      title: PA Info by IPA
      description: Denomination, fiscal code, pec, email, tel, www site, ...
      type: object
      required:
        - id
        - name
        - taxId
        - generalContacts
      properties:
        id:
          $ref: '#/components/schemas/SelfCarePaId'
        name:
          type: string
          minLength: 1
        taxId:
          description: codice fiscale
          type: string
          minLength: 1
        ipaCode:
          description: codice IPA
          type: string
          minLength: 1
        sdiCode:
          description: codice SDI
          type: string
          minLength: 1
        agreementDate:
          description: data sottoscrizione accordo
          example: '2022-07-27T12:22:33.444Z'
          type: string
          format: date-time
        generalContacts:
          $ref: '#/components/schemas/PaContacts'
    PaContacts:
      title: Contact Information
      description: pec, email, tel, www site, ...
      type: object
      properties:
        pec:
          type: string
          format: email
          minLength: 1
        email:
          type: string
          format: email
          minLength: 1
        tel:
          type: string
          pattern: ^\\+?([0-9]|-)*
          minLength: 1
          maxLength: 20
        web:
          type: string
          format: uri
          pattern: http.*
          minLength: 1
        registeredOffice:
          type: string
          description: sede legale
          minLength: 1
    PaGroupList:
      title: Groups defined in Self Care
      description: Contains the list of groups defined in SelfCare
      type: array
      items:
        $ref: '#/components/schemas/PaGroup'
    PaGroup:
      title: Group defined in Self Care
      description: Contains the name list of groups defined in SelfCare
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        status:
          $ref: '#/components/schemas/PaGroupStatus'
    PaGroupStatus:
      title: Status of group defined in Self Care
      description: Contains the name list of groups defined in SelfCare
      type: string
      enum:
        - ACTIVE
        - SUSPENDED
    PgGroupList:
      title: Groups defined in Self Care PG (Notifiche digitali)
      description: Contains the list of groups defined in SelfCare PG (Notifiche digitali)
      type: array
      items:
        $ref: '#/components/schemas/PgGroup'
    PgGroup:
      title: Group defined in Self Care PG (Notifiche digitali)
      description: Contains the name list of groups defined in SelfCare PG (Notifiche digitali)
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        status:
          $ref: '#/components/schemas/PgGroupStatus'
    PgGroupStatus:
      title: Status of group defined in Self Care PG (Notifiche digitali)
      description: Contains the status of groups defined in SelfCare PG (Notifiche digitali)
      type: string
      enum:
        - ACTIVE
        - SUSPENDED
    SelfCarePaId:
      title: The PA id used by self care
      description: An unique ID that identify a Public Administration
      type: string
      minLength: 1
      maxLength: 50
      pattern: ^[ -~ ]*$
    ProblemError:
      properties:
        code:
          description: Internal code of the error, in human-readable format
          example: PN_PARAMETER_TOO_LONG | PN_PARAMETER_TOO_SHORT | PN_DUPLICATE_ENTRY | etc...
          type: string
        element:
          description: Parameter or request body field name for validation error
          example: body.order.item[2].quantity
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 1024
          type: string
      required:
        - code
    Problem:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: integer
          format: int32
          example: 503
          maximum: 600
          minimum: 100
          exclusiveMaximum: true
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: ^[ -~]{0,64}$
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: ^.{0,4096}$
          type: string
        traceId:
          description: Internal support identifier associated to error
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
        timestamp:
          description: date and time referred to UTC
          example: '2022-07-27T12:22:33.444Z'
          type: string
          format: date-time
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ProblemError'
      required:
        - status
        - errors
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
