openapi: 3.0.1
info:
  title: API di integrazione con PA IN MVP
  version: v1
  description: Api di integrazione per la determinazione degli utenti nel contesto MVP
  license:
    name: PagoPA PN license
    url: http://pn.pagopa.it
servers:
  - url: https://placeholder
    description: placeholder
tags:
  - name: mvpContext
    description: Api per de
paths:
  '/ext-registry-b2b/pa/v1/mvp-valid-users':
    post:
      operationId: checkValidUsers
      summary: List of valid users for the MPV context
      description: Return if the user are in the context of MVP or not
      tags:
        - mvpContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MvpUser'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
components:
  schemas:
    TaxId:
      type: string
      x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL
    MvpUser:
      type: object
      required:
        - taxId
        - valid
      properties:
        taxId:
          type: string
        valid:
          type: boolean

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key