openapi: 3.0.1
info:
  title: API di integrazione con PA IN MVP
  version: v1
  description: Api di integrazione per la determinazione degli utenti nel contesto MVP
  license:
    name: PagoPA PN license
    url: http://pn.pagopa.it
servers:
  - url: https://placeholder
    description: placeholder
tags:
  - name: mvpContext
    description: Api per de
paths:
  '/ext-registry-b2b/pa/v1/mvp-valid-users':
    post:
      operationId: checkValidUsers
      summary: List of valid users for the MPV context
      description: Return if the user are in the context of MVP or not
      tags:
        - mvpContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MvpUser'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: 'pn-errors.yaml#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'pn-errors.yaml#/components/schemas/Problem'
components:
  schemas:
    TaxId:
      type: string
      minLength: 16
      maxLength: 16
      pattern: "^[A-Z]{6}[0-9LMNPQRSTUV]{2}[A-Z]{1}[0-9LMNPQRSTUV]{2}[A-Z]{1}[0-9LMNPQRSTUV]{3}[A-Z]{1}$"
    MvpUser:
      type: object
      required:
        - taxId
        - valid
      properties:
        taxId:
          type: string
        status:
          type: string
          description: >
            Stato attivazione invio messaggi tramite AppIo:
            * APPIO_NOT_ACTIVE: AppIo isn't active for the user.
            * APPIO_ACTIVE_PN_NOT_ACTIVE: Appio is active for the user, but messages from Piattaforma Notifiche is not active.
            * APPIO_ACTIVE_PN_ACTIVE: Appio is active for the user and messages from Piattaforma Notifiche is active.
          enum:
            - APPIO_NOT_ACTIVE
            - PN_NOT_ACTIVE
            - PN_ACTIVE

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key