AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

  CdcKinesisSourceStreamArn:
    Type: String
    Description: "Where to send CDC"

Conditions:
  Never: !Equals [ 'true', 'false' ]


Resources:
  IOMessagesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TableName: !Sub '${ProjectName}-IOMessages'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true      

  OnboardInstitutionsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TableName: !Sub '${ProjectName}-OnboardInstitutions'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "onlyRootStatus"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastUpdate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "onlyRootStatus-lastUpdate-gsi"
          KeySchema:
            - AttributeName: "onlyRootStatus"
              KeyType: "HASH"
            - AttributeName: "lastUpdate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "status-lastUpdate-gsi"
          KeySchema:
            - AttributeName: "status"
              KeyType: "HASH"
            - AttributeName: "lastUpdate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CostComponentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-CostComponents'
      AttributeDefinitions:
        - AttributeName: 'pk'
          AttributeType: 'S'
        - AttributeName: 'sk'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'pk'
          KeyType: 'HASH'
        - AttributeName: 'sk'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CostUpdateResultTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-CostUpdateResult'
      AttributeDefinitions:
        - AttributeName: 'pk'
          AttributeType: 'S'
        - AttributeName: 'sk'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'pk'
          KeyType: 'HASH'
        - AttributeName: 'sk'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      # Kinesis CDC source
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  SenderConfigurationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-SenderConfiguration'
      AttributeDefinitions:
        - AttributeName: 'pk'
          AttributeType: 'S'
        - AttributeName: 'sk'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'pk'
          KeyType: 'HASH'
        - AttributeName: 'sk'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PnExternalRegistriesLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-external-registries'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  PnExternalRegistriesInsertTriggerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-external-registries-trigger-lambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:

  # Table parameters
  IOMessagesTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref IOMessagesTable
  IOMessagesTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${IOMessagesTable.Arn}'

  OnboardInstitutionsTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref OnboardInstitutionsTable
  OnboardInstitutionsTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${OnboardInstitutionsTable.Arn}'

  CostComponentsTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref CostComponentsTable
  CostComponentsTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${CostComponentsTable.Arn}'

  CostUpdateResultTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref CostUpdateResultTable

  CostUpdateResultTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${CostUpdateResultTable.Arn}'

  SenderConfigurationTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref SenderConfigurationTable
  SenderConfigurationTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${SenderConfigurationTable.Arn}'

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnExternalRegistriesLogGroup.Outputs.LogGroupName
  PnExternalRegistriesTriggerLambdaName:
    Value: !Sub "${ProjectName}-external-registries-trigger-lambda"
