AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

Conditions:
  Never: !Equals [ 'true', 'false' ]


Resources:
  OptInSentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-OptInSent'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: pnInfraFeature
          Value: pnStorage
        - Key: pnMicroservice
          Value: !Sub '${ProjectName}-OptInSent'

  OnboardInstitutionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-OnboardInstitutions'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastUpdate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "status-lastUpdate-gsi"
          KeySchema:
            - AttributeName: "status"
              KeyType: "HASH"
            - AttributeName: "lastUpdate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      Tags:
        - Key: pnInfraFeature
          Value: pnStorage
        - Key: pnMicroservice
          Value: !Sub '${ProjectName}-OnboardInstitutions'


Outputs:

  # Table parameters
  OptInSentTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref OptInSentTable
  OptInSentTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${OptInSentTable.Arn}'

  OnboardInstitutionsTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref OnboardInstitutionsTable
  OnboardInstitutionsTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${OnboardInstitutionsTable.Arn}'
