AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

Conditions:
  Never: !Equals [ 'true', 'false' ]


Resources:
  IOMessagesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TableName: !Sub '${ProjectName}-IOMessages'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true      

  OnboardInstitutionsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TableName: !Sub '${ProjectName}-OnboardInstitutions'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastUpdate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "status-lastUpdate-gsi"
          KeySchema:
            - AttributeName: "status"
              KeyType: "HASH"
            - AttributeName: "lastUpdate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"

  PnExternalRegistriesLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-external-registries'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  PnExternalRegistriesInsertTriggerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-external-registries-trigger-lambda"
        LogGroupPrefix: '/aws/lambda'

Outputs:

  # Table parameters
  IOMessagesTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref IOMessagesTable
  IOMessagesTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${IOMessagesTable.Arn}'

  OnboardInstitutionsTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref OnboardInstitutionsTable
  OnboardInstitutionsTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${OnboardInstitutionsTable.Arn}'

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnExternalRegistriesLogGroup.Outputs.LogGroupName
  PnExternalRegistriesTriggerLambdaName:
    Value: !Sub "${ProjectName}-external-registries-trigger-lambda"

