/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pn.ext.registries.pa.api;

import it.pagopa.pn.ext.registries.pa.model.PaInfoDto;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-14T15:48:36.815856800+01:00[Europe/Berlin]")
@Validated
public interface InfoPaApi {

    /**
     * GET /ext-registry/pa/v1/activated-on-pn/{id} : Retrieve detailed information about one PA
     * Used by the Notification detail page
     *
     * @param id The identifier of one PA (required)
     * @return OK (status code 200)
     *         or Invalid input (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/ext-registry/pa/v1/activated-on-pn/{id}",
        produces = { "application/json", "application/problem+json" }
    )
    default ResponseEntity<PaInfoDto> _getOnePa(
        @Size(min = 1)  @PathVariable("id") String id
    ) {
        return getOnePa(id);
    }

    // Override this method
    ResponseEntity<PaInfoDto> getOnePa(String id);
        


    /**
     * GET /ext-registry/pa/v1/activated-on-pn : List PA that use PN
     * Use with API to implement PA choose in domicile and mandate creation pages.
     *
     * @param paNameFilter Se valorizzato indica (optional)
     * @return OK (status code 200)
     *         or Invalid input (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/ext-registry/pa/v1/activated-on-pn",
        produces = { "application/json", "application/problem+json" }
    )
    default ResponseEntity<List<Object>> _listOnboardedPa(
        @Pattern(regexp = "[A-Za-z0-9 _]*") @Size(min = 3)  @Valid @RequestParam(value = "paNameFilter", required = false) String paNameFilter
    ) {
        return listOnboardedPa(paNameFilter);
    }

    // Override this method
    ResponseEntity<List<Object>> listOnboardedPa(String paNameFilter);
        

}
